using System.Xml.Linq;

namespace Rug.Loading
{
    /// <summary>
    /// Loadable Interface.
    /// </summary>
    /// <autogeneratedoc />
    public interface ILoadable
    {
        /// <summary>
        /// Loads this instance from the specified node.
        /// </summary>
        /// <param name="node">The node.</param>
        /// <autogeneratedoc />
        void Load(LoadContext context, XElement node);

        /// <summary>
        /// Saves this instance to the specified element.
        /// </summary>
        /// <param name="element">The element to save to.</param>
        /// <autogeneratedoc />
        void Save(LoadContext context, XElement element);
    }
}