using System;

namespace Rug.Loading
{
    /// <summary>
    /// XML load name attribute.
    /// </summary>
    /// <autogeneratedoc />
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Field | AttributeTargets.Property)]
    public class NameAttribute : Attribute
    {
        /// <summary>
        /// The name of the XML type.
        /// </summary>
        /// <autogeneratedoc />
        public readonly string Name;

        /// <summary>
        /// Initializes a new instance of the <see cref="NameAttribute"/> class.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <autogeneratedoc />
        public NameAttribute(string name)
        {
            Name = name;
        }
    }
}