namespace Rug.Osc.Ahoy
{
    public static class AhoyConstants
	{
        /// <summary>
        /// Ahoy broadcast port as defined in protocol. The ASCII value of the MSB and LSB are 'a' and 'h' respectively.
        /// </summary>
        public const int AhoyBroadcastPort = 0x6168; // 24936

        /// <summary>
        /// Ahoy response port as defined in protocol. The ASCII value of the MSB and LSB are 'o' and 'y' respectively.
        /// </summary>
        public const int AhoyResponsePort = 0x6F79; // 28537

        /// <summary>
        /// The address
        /// </summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for Address
        public const string Address = "/ahoy";
    }
}
